version: "3"
 
services:
  db:
    image: postgres:10-alpine
    container_name: db-container 
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
      - POSTGRES_DB=test_db
      - DATABASE_HOST=localhost
    volumes:
      - ./db:/docker-entrypoint-initdb.d
